@startuml

class Menu {
    +showMenu()
    +showResults()
}

class Calculator {
    - operation: IOperation

    + setOperation(operation: IOperation): void
    + calculate(nums: List<float>): float
}

interface IOperation {
    - operation: void
    + calculate(nums: List<float>): float
}

class Add {
    - operation: 0
    + calculate(nums: List<float>): float
}

class Sub {
    - operation: 1
    + calculate(nums: List<float>): float
}

class Multiply {
    - operation: 2
    + calculate(nums: List<float>): float
}

class Divide {
    -operation: 3
    + calculate(nums: List<float>): float
}

class GenerateNums {
    + separateNums(input: string): List<float>
}

Menu -> Calculator
Calculator -> IOperation
IOperation -> GenerateNums
IOperation -> Add
IOperation -> Sub
IOperation -> Multiply
IOperation -> Divide
@enduml

